"""Create player and player season tables

Revision ID: 908aa80e0ac6
Revises: 
Create Date: 2026-08-04 22:01:02.997656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908aa80e0ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.String(length=30), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('team_abbrev', sa.String(length=10), nullable=True),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('games_played', sa.BigInteger(), nullable=True),
    sa.Column('minutes_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('rebounds_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('steals_per_game', sa.Float(), nullable=True),
    sa.Column('blocks_per_game', sa.Float(), nullable=True),
    sa.Column('turnovers_per_game', sa.Float(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('free_throw_percentage', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('collected_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'season_type', name='unique_player_season')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_seasons')
    op.drop_table('players')
    # ### end Alembic commands ###
